services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: database_escola
      MYSQL_ROOT_PASSWORD: tempPassword
    ports:
      - 3306:3306
    volumes:
      - ./.database:/var/lib/mysql
    